name: homies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.3
  convex_bottom_bar: ^3.2.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.1
  flutter_local_notifications: ^17.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  lottie: ^3.1.0
  rxdart: ^0.27.7
  http: ^1.2.1
  overlay_support: ^2.1.0
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/
   
