name: homies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  lottie: ^3.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
   
